export PS1='[\u@\h \W]\$ '

alias master="docker-compose -f ~/docker/docker-compose.yml exec sm"
alias master_up="docker-compose -f ~/docker/docker-compose.yml up -d sm"
alias master_down="docker-compose -f ~/docker/docker-compose.yml down sm"
alias master_restart="docker-compose -f ~/docker/docker-compose.yml restart sm"
