version: "2"

services:
  # web:
  #  image: nginx
  #  volumes:
  #    - ./html:/usr/share/nginx/html
  #  ports:
  #    - "80:80"
  #  environment:
  #    - NGINX_PORT=80
  sm:
    build: 
      context: ./
      dockerfile: Dockerfile.master
    privileged: true
    ports:
      - "4505"
      - "4506"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./master.d:/etc/salt/master.d/:z"
  centos:
    build:
      context: ./
      dockerfile: Dockerfile.minion
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"
  ubuntu:
    build:
      context: ./
      dockerfile: Dockerfile.minion-ubu
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"
