FROM centos:7

ENV container docker

COPY ./ss.repo /etc/yum.repos.d/saltstack.repo

RUN rpm --import https://repo.saltstack.com/yum/redhat/7/x86_64/archive/2018.3.4/SALTSTACK-GPG-KEY.pub

RUN yum -y install salt-master salt-minion; yum clean all; systemctl enable salt-master salt-minion

COPY ./ss.master.conf /etc/salt/minion.d/master.conf

CMD ["/usr/sbin/init"]
