FROM jrei/systemd-ubuntu:18.04

ENV container docker

#COPY ./ss.repo /etc/yum.repos.d/saltstack.repo

#RUN rpm --import https://repo.saltstack.com/yum/redhat/7/x86_64/archive/2018.3.4/SALTSTACK-GPG-KEY.pub

#RUN yum -q -y install salt-minion; yum clean all; systemctl enable salt-minion

RUN apt-get install salt-minion

CMD ["/usr/sbin/init"]
