version: "3"

# https://hub.docker.com/r/centos/systemd/
# https://hub.docker.com/r/jrei/systemd-ubuntu

services:
  sm:
    image: kajigga/sm-cn-7:0.3
    hostname: master
    privileged: true
    ports:
      - "4505"
      - "4506"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./master.d:/etc/salt/master.d/:z"
      - "./minion.d:/etc/salt/minion.d/:z"
      #- "../sse_installer/salt:/srv/salt:ro"

  centos:
    hostname: ubuntu
    image: kajigga/smin-cn-7:0.3
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"

  ubuntu:
    hostname: ubuntu
    image: kajigga/smin-ub-18:0.3
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"

  raas:
    hostname: raas
    image: kajigga/smin-cn-7:0.3
    privileged: true
    ports:
      - "4505"
      - "4506"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"
    depends_on:
      - redis
      - pg

  redis:
    image: redis
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf:ro"

  pg:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: bonkerz
      POSTGRES_USER: sseapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata:z"
