version: "3"

# https://hub.docker.com/r/centos/systemd/
# https://hub.docker.com/r/jrei/systemd-ubuntu

services:
  sm:
    image: kajigga/sm-cn-7:0.3
    hostname: master
    privileged: true
    ports:
      - "4505"
      - "4506"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./master.d:/etc/salt/master.d/:z"
      - "./minion.d:/etc/salt/minion.d/:z"
      - "./sse_installer:/srv:z"

  centos:
    hostname: centos
    image: kajigga/smin-cn-7:0.3
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"

  ubuntu:
    hostname: ubuntu
    image: kajigga/smin-ub-18:0.3
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"

  raas:
    hostname: raas
    image: kajigga/smin-cn-7:0.3
    privileged: true
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"
    depends_on:
      - redis
      - pg

  redis:
    image: redis:5.0-alpine
    command: redis-server --requirepass def456

  pg:
    image: kajigga/smin-cn-7:0.3
    hostname: pg
    privileged: true
    ports:
      - "5432"
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./minion.d:/etc/salt/minion.d/:z"
    # image: postgres:9.6
    # restart: always
    # environment:
    #   POSTGRES_PASSWORD: bonkerz
    #   POSTGRES_USER: sseapi
    #   PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data/pgdata:z"
